base_url = "https://forge-theme.wingelaar.be"
title = "Forge"
description = "Forge theme for Zola"
compile_sass = true
ignored_content = ["*.dnr.md"]

[markdown]
highlight_code = true
highlight_theme = "Tomorrow"
render_emoji = true
smart_punctuation = true

[extra]
author = { name = "Ivo C.S. Wingelaar" }
katex = true
menu = [
    {url = "/blog/", name = "Blog"},
    {url = "/about/", name = "About"},
    {url = "/contact/", name = "Contact"},
]
branding_logo_path = "forge.svg"
hero_logo = "forge-inv.svg"
hero_content = "hero.dnr.md"
