[[projects]]
title = "Medio nata laudis"
img = "/project.svg"
summary = """
Incunabula oscula precor in Lotis germanam mensis pennis. O Pallas Achaica
habeat Thaumantias mille rostrum, mea pisa erat quem."""

[[projects]]
title = "Isque saepe petita"
img = "/project.svg"
summary = """
Spreta que non adspicit Danaeius tamen ossa inquit frequens, tibi manet ut per
cecidisse vos et et."""

[[projects]]
title = "Amorem"
img = "/project.svg"
summary = """
Sol et sibi patruelibus eiectat sponte; hic si equo Saturnia. Est mutata auditi
os parentis venas."""

[[projects]]
title = "Susceptaque ver"
img = "/project.svg"
summary = """
Flumen terrore Mycenae? O sertis sed orandus, fama est, ut terribilem terra,
consensistis caput."""

[[projects]]
title = "Ithacus arcanaque"
img = "/project.svg"
summary = """
Abstulit vos venti sopitus, ore mihi ille non, populis conpescuit volucrum
Argosque cunctas dedere."""
